#! /bin/sh

killall sxhkd; sxhkd &
killall picom; picom &
killall dunst; dunst &
nitrogen --restore &
redshift -x && redshift -O 4000k &
xsetroot -cursor_name left_ptr &

bspc monitor -d NETWORK CALENDAR STORAGE TERMINAL MUSICS DATABASE SYSTEM
$HOME/.config/polybar/launch.sh &
bspc config window_gap           10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer false
bspc config border_width 0


bspc rule -a conky-rofi state=floating layer=above
bspc rule -a feh state=floating layer=normal
bspc rule -a Gifview state=floating

